# This task is used to mount a filesystem via NFS.
# 
# Variables you need to define:
# nfsserver:   the nfs server to mount from
# nfspath:     the remote filesystem to mount from the nfs server
# nfsmount:    the directory where you want to mount the filesystem.
# nfsoptions:  options to use when mounting the filesystem. If not
#              defined, `rw,sync` will be used.
#
# Please note that the task will check if the {{nfsmount}} directory
# exists and create it otherwise.
#

- hosts: moll-all
  vars:
    nfsserver: llit-nfs
    nfspath: /nfs
    nfsmount: /nfs
    nfsoptions: 'rw,sync'
  tasks:
   - name: install nfs client
     action: yum pkg=nfs-utils state=present

   - name: Ensure rpcbind is running (CentOS)
     action: service name=rpcbind state=started enabled=yes

   - name: Ensure {{nfsmount}} directory exists
     action: file path={{nfsmount}} state=directory

   - shell: if [ -z "$nfsoptions" ]; then  echo rw,sync,nfsvers=3; else echo $nfsoptions; fi
     register: _nfsopts
     connection: local

   - name: configure /etc/fstab on clients
     action: mount name={{nfsmount}} src={{nfsserver}}:{{nfspath}} fstype=nfs opts={{_nfsopts.stdout}} state=mounted
